name: square_in_app_payments_example
description: Demonstrates how to use the square_in_app_payments plugin.

version: 1.1.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0
  uuid: ^2.0.0

dev_dependencies:
  square_in_app_payments:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/
